### ISSUE TITLE
strapi-sdk-javascript cannot communicate with 3.0.0_beta.5 server

### ISSUE THREAD

**Issue by kktam** [strapi/strapi-sdk-javascript#75]
**Informations**
- **Node.js version**: v10.13.0
- **npm version**: 6.9.0
- **Strapi version**:   client 3.0.0_alpha.27,  server 3.0.0_beta.5
- **Strapi-sdk-javascript version**: 0.3.1
- **Browser or Node.js**:  Chrome

**What is the current behavior?**

When some navigate to http://localhost:3000, the client node server display following error:

```
> @ dev C:\Users\n\code\strapi\deliveroo
> node server.js

> Ready on http://localhost:3000
[ event ] build page: /
[ wait ]  compiling ...
TypeError: Cannot assign to read only property '__esModule' of object '#<Object>'
    at C:\Users\n\code\strapi\deliveroo\node_modules\apollo-boost\lib\bundle.cjs.js:127:74
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\n\code\strapi\deliveroo\node_modules\apollo-boost\lib\bundle.cjs.js:127:36)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\n\code\strapi\deliveroo\node_modules\next-apollo\dist\initApollo.js:12:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
[ error ] TypeError: Cannot assign to read only property '__esModule' of object '#<Object>'
    at C:\Users\n\code\strapi\deliveroo\node_modules\apollo-boost\lib\bundle.cjs.js:127:74
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\n\code\strapi\deliveroo\node_modules\apollo-boost\lib\bundle.cjs.js:127:36)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\n\code\strapi\deliveroo\node_modules\next-apollo\dist\initApollo.js:12:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
TypeError: Cannot assign to read only property '__esModule' of object '#<Object>'
    at C:\Users\n\code\strapi\deliveroo\node_modules\apollo-boost\lib\bundle.cjs.js:127:74
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\n\code\strapi\deliveroo\node_modules\apollo-boost\lib\bundle.cjs.js:127:36)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\n\code\strapi\deliveroo\node_modules\next-apollo\dist\initApollo.js:12:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
[ error ] TypeError: Cannot assign to read only property '__esModule' of object '#<Object>'
    at C:\Users\n\code\strapi\deliveroo\node_modules\apollo-boost\lib\bundle.cjs.js:127:74
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\n\code\strapi\deliveroo\node_modules\apollo-boost\lib\bundle.cjs.js:127:36)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\n\code\strapi\deliveroo\node_modules\next-apollo\dist\initApollo.js:12:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
TypeError: Cannot assign to read only property '__esModule' of object '#<Object>'
    at C:\Users\n\code\strapi\deliveroo\node_modules\apollo-boost\lib\bundle.cjs.js:127:74
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\n\code\strapi\deliveroo\node_modules\apollo-boost\lib\bundle.cjs.js:127:36)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\n\code\strapi\deliveroo\node_modules\next-apollo\dist\initApollo.js:12:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

**Steps to reproduce the problem**
Follow [https://blog.strapi.io/strapi-next-setup/](https://blog.strapi.io/strapi-next-setup/) to build a deliveroo client and server using Strapi 3.0.0_alpha.x.

Follow migration guide, to rebuild the deliveroo server using strapi 3.0.0_beta.5.
Connect deliveroo client to new deliveroo server.

**What is the expected behavior?**
Somewhat working so the developer can debug.

**Suggested solutions**

**Confirm**
- [ ] I'm sure that this issue hasn't already been referenced

**Comment by kktam** [comment]
I recheck the reproduce steps and found that the project dependencies does not work with npm but only with yarn.

after rebuilding Next.js deliveroo example I got a lesser but different React error. I am not sure if it is related to fact that the host is now installed with Strapi beta (npm install strapi@beta -g)

Here is new error message after starting client with 'yarn, yarn dev'

```
[ wait ]  compiling ...
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    in MyApp
    in Context.Provider
    in ApolloProvider
    in RenderPromisesProvider
TypeError: Cannot read property 'pathname' of undefined
    at Object.makePublicRouterInstance (C:\Users\ntam\code\strapi\deliveroo\node_modules\next\dist\client\router.js:148:23)
    at MyApp.getChildContext (C:\Users\ntam\code\strapi\deliveroo\.next\server\static\development\pages\_app.js:1925:26)
    at processChild (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-dom\cjs\react-dom-server.node.development.js:2974:29)
    at resolve (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-dom\cjs\react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-dom\cjs\react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-dom\cjs\react-dom-server.node.development.js:3161:29)
    at renderToStaticMarkup (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-dom\cjs\react-dom-server.node.development.js:3661:27)
    at process (C:\Users\ntam\code\strapi\deliveroo\node_modules\react-apollo\react-apollo.cjs.js:1044:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ event ] disposing inactive page(s): /next/dist/pages/_error
```
